[governance]
address = "DAO Address"
description = "Testing DAO of aries."
creator-nickname = ""
logo-url = "DAO governance logo url."
bg-img-url = "Backgroup image url for DAO Page on OrderDAO."

[links]
dao-homepage = ""
twitter = "https://twitter.com/AriesMarkets"
discord = "https://discord.gg/ariesmarkets"
