[governance]
address = "0x70301c2da60b23986cc47fa74b6028fac61bdea4725a526de24baaeda4b3c378"
description = "We are all sh*tcoins"
creator-nickname = "DooDoo"
logo-url = "https://uploads-ssl.webflow.com/60536b901b879c2f395d75d0/660d5c255bd8f3eb1d6df6e6_logo.png"
bg-img-url = "https://uploads-ssl.webflow.com/60536b901b879c2f395d75d0/660d5c2527ef13f61c379c45_banner.png"

[links]
dao-homepage = ""
twitter = "https://twitter.com/doodoocoin"
discord = "https://discord.com/invite/44QgPFHYqs"
