[governance]
address = "0xc50f1bff8a05c9f4737bb0d2361440fd0c4c6967eae45eb2a1a59f56968cc1d3"
description = "We are all sh*tcoins"
creator-nickname = "DooDoo"
logo-url = "https://uploads-ssl.webflow.com/60536b901b879c2f395d75d0/660d5c255bd8f3eb1d6df6e6_logo.png"
bg-img-url = "https://uploads-ssl.webflow.com/60536b901b879c2f395d75d0/660d5c2527ef13f61c379c45_banner.png"

[links]
dao-homepage = "https://doodoo.io/"
twitter = "https://twitter.com/doodoocoin"
discord = "https://discord.com/invite/44QgPFHYqs"
