[governance]
address = "0x585ebcde6a9c00de22a4b5f392f4b21a173b772e5d8111269f81507303421a7f"
description = "Spooks"
creator-nickname = "Spooks"
logo-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/spooks-logo-testnet.png"
bg-img-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/spooks-bg-testnet.png"

[links]
twitter = "https://twitter.com/aptoslabs/"
discord = "https://discord.com/invite/aptoslabs"
