[governance]
address = "0xb993b92d378c3a68ff827d7ba920b968075d2334d89f71b59cb98ee0bae64fd9"
description = "Moonbirds u"
creator-nickname = "PROOF_XYZ"
logo-url = "https://i.seadn.io/gae/yNi-XdGxsgQCPpqSio4o31ygAV6wURdIdInWRcFIl46UjUQ1eV7BEndGe8L661OoG-clRi7EgInLX4LPu9Jfw4fq0bnVYHqg7RFi?auto=format&w=2048"
bg-img-url = "https://i.seadn.io/gcs/files/89f0cd4457af5632e66fb44bf43309cd.png?auto=format&w=2048"

[links]
twitter = "https://twitter.com/aptoslabs/"
discord = "https://discord.com/invite/aptoslabs"
