[governance]
address = "0xa884f7a49a945179d7e48e1fb7b685b75ac6100c1fe814f46c153f7865e73a9f"
description = "Aliver's DAO"
creator-nickname = "aliver"
logo-url = "https://ipfs.bluemove.io/uploads/aptos-dragons/logo.webp"

[links]
dao-homepage = "https://ariesmarkets.xyz/"
twitter = "https://twitter.com/AriesMarkets"
discord = "https://discord.gg/ariesmarkets"