[governance]
address = "0x1965435479d04eafbcad17c9c9b79d28f7887b2df18ff8f0dd1d189139e84e09"
description = "Spooks"
creator-nickname = "Spooks"
logo-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/spooks-logo-testnet.png"
bg-img-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/spooks-bg-testnet.png"

[links]
twitter = "https://twitter.com/SpooksLabs"
discord = "http://discord.gg/spooks"
