[governance]
address = "0x25a1faff50a9df85a9976f533f61069d8f83d0f65941b38a7151561738db11fa"
description = "Lemur Lounge"
creator-nickname = "Lemur Lounge"
logo-url = "https://files.slack.com/files-pri/T02BEAB9XEC-F04QH1KJM1Q/photo_2023-02-21_13.32.23.jpeg"
bg-img-url = "https://files.slack.com/files-tmb/T02BEAB9XEC-F04QVLQ9NEM-f0ec402935/photo_2023-02-21_13.37.13_720.jpg"

[links]
dao-homepage = "https://ariesmarkets.xyz/"
twitter = "https://twitter.com/AriesMarkets"
discord = "https://discord.gg/ariesmarkets"
