[governance]
address = "0x25a1faff50a9df85a9976f533f61069d8f83d0f65941b38a7151561738db11fa"
description = "Lemur Lounge"
creator-nickname = "Lemur Lounge"
logo-url = "https://i.328888.xyz/2023/02/21/gwbkF.jpeg"
bg-img-url = "https://i.328888.xyz/2023/02/21/gwHaZ.jpeg"

[links]
dao-homepage = "https://ariesmarkets.xyz/"
twitter = "https://twitter.com/AriesMarkets"
discord = "https://discord.gg/ariesmarkets"
