[governance]
address = "0x25a1faff50a9df85a9976f533f61069d8f83d0f65941b38a7151561738db11fa"
description = "Lemur Lounge"
creator-nickname = "Lemur Lounge"
logo-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/lemur-lounge-logo-testnet.jpeg"
bg-img-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/lemur-lounge-bg-testnet.jpeg"

[links]
dao-homepage = "https://ariesmarkets.xyz/"
twitter = "https://twitter.com/AriesMarkets"
discord = "https://discord.gg/ariesmarkets"
