[governance]
address = "0x3b3688ac594896e9963c4654da2f69b2c5c0455dfee65337ff319f0f61e22215"
description = "Pontem Space Pirates"
creator-nickname = "Pontem Space Pirates"
logo-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/pontem_space_pirates_logo.png"
bg-img-url = "https://raw.githubusercontent.com/Aries-Markets/aptos-nft-dao-registry/main/release/images/pontem_space_pirates_bg.png"

[links]
dao-homepage = "https://pontem.network/"
twitter = "https://twitter.com/PontemNetwork"
discord = "https://discord.gg/44QgPFHYqs"
