[governance]
address = "0xf1702eb3bcd85119d75a9f36e2b307d3e1b3a048768ede1b278f343b93b0dd8c"
description = "Testing DAO of aries."
creator-nickname = "Aries Markets"
logo-url = "https://ariesmarkets.xyz/assets/logo-aries.70664ee8.svg"

[links]
twitter = "https://twitter.com/AriesMarkets"
discord = "https://discord.gg/ariesmarkets"